// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
//
//   Triangle    Tn = n(n + 1) / 2    1, 3, 6, 10, 15
//   Pentagonal  Pn = n(3n - 1) / 2   1, 5, 12, 22, 35
//   Hexagonal   Hn = n(2n - 1)       1, 6, 15, 28, 45
//
// It can be verified that T(285) = P(165)= H(143) = 40755.
//
// Find the next triangle number that is also pentagonal and hexagonal.

#include "common.h"

u64 triangular(u64 n)
{
    return n * (n + 1) / 2;
}

u64 pentagonal(u64 n)
{
    return n * (3 * n - 1) / 2;
}

u64 hexagonal(u64 n)
{
    return n * (2 * n - 1);
}

void increment_the_smallest(u64 nvalues[3], u64 *pointers[3])
{
    u64 max = ULONG_MAX;
    u64 idx = -1;

    for (i32 i = 0; i < 3; i++) {
        if (max > nvalues[i]) {
            max = nvalues[i];
            idx = i;
        }
    }

    assert(idx >= 0);

    (*pointers[idx])++;
}

int main(int argc, char **argv)
{
    u64 t = 0, p = 0, h = 0;

    for (;;) {
        u64 tn = triangular(t);
        u64 pn = pentagonal(p);
        u64 hn = hexagonal(h);

        if (tn == pn && pn == hn) {
            printf("T(%lu) == P(%lu) == H(%lu) == %lu\n",
                t, p, h, tn
            );

            // Break if we find an equivalent triangular number greater than T(285).
            if (t > 285) {
                break;
            }

            t++;
            p++;
            h++;
        } else {
            u64 nvalues[3] = {
                tn, pn, hn
            };
            u64 *pointers[3] = {
                &t, &p, &h
            };

            increment_the_smallest(nvalues, pointers);
        }
    }

    printf("T(%lu)\n", t);
}
